# Generated by Django 5.0.6 on 2024-06-27 16:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='saved_images/')),
                ('percentage_video_created', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='saved_videos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
